"""Initial migration.

Revision ID: 7af146f11dbc
Revises: 
Create Date: 2023-12-22 22:21:18.297333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7af146f11dbc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archived_meme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meme_url', sa.String(length=255), nullable=False),
    sa.Column('subreddit', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('archived_meme')
    # ### end Alembic commands ###
